### ISSUE TITLE
Background scheduling requires the GIL

### ISSUE THREAD

**Issue by Lothiraldan** [mlco2/code-carbon#17]
By working on the integration between code-carbon and the Comet Python SDK, I saw that the apscheduler BackgroundScheduler was using threads under the hood. This might causes issues with some machine learning libraries that execute some C code during a long time without releasing the GIL, we had a similar issue in the past.

Here is a reproduction script which runs in about 3 minutes and 40 seconds on my laptop with Python 3.7.5. I am using `re.match` for mimicking a piece of code holding the GIL for a certain amount of time:

```python
import time
import re
from codecarbon import EmissionsTracker

tracker = EmissionsTracker()
tracker.start()

time.sleep(15)

re.match(r"(a?){32}a{32}", "a" * 32)

time.sleep(15)

tracker.stop()
```

When running with the following diff:

```diff
diff --git a/codecarbon/emissions_tracker.py b/codecarbon/emissions_tracker.py
index 7b07ea2..66283d7 100644
--- a/codecarbon/emissions_tracker.py
+++ b/codecarbon/emissions_tracker.py
@@ -155,6 +155,7 @@ class BaseEmissionsTracker(ABC):
         every `self._measure_power` seconds.
         :return: None
         """
+        print("Measure power", time.time())
         self._total_energy += Energy.from_power_and_time(
             power=self._hardware.total_power,
             time=Time.from_seconds(self._measure_power_secs),
```

Here is the output that highlight the fact that the background job was not scheduled while the `re.match` was running:

```
Measure power 1599575654.264812
Run time of job "BaseEmissionsTracker._measure_power (trigger: interval[0:00:15], next run at: 2020-09-08 16:34:29 CEST)" was missed by 0:00:04.694579
Measure power 1599575834.2660286
```

I think we need to clarify which level of precision that we need.

**Comment by Lothiraldan** [comment]
@kngoyal Here is an example of using a background process and process information at the end:
```
import time
import random
import queue
from multiprocessing import Process, Queue, Event

def measurement_process(event: Event, queue: Queue):
    while event.is_set() is False:
        measure = random.random()
        queue.put(measure)
        time.sleep(1)


# Start the background process
q: Queue = Queue()
e: Event = Event()
p = Process(target=measurement_process, args=(e, q))

p.start()

print(f"{p} started")

# Do the computation
time.sleep(30)

# Properly cleans the background process
e.set()
p.join(10)

# Empty the queue
total_sum = 0
try:
    while True:
        item = q.get_nowait()
        total_sum = total_sum + item
except queue.Empty:
    pass

print(f"Total sum {total_sum}")
```

**Comment by kngoyal** [comment]
Made a fix [here](https://github.com/mlco2/code-carbon/pull/34) by taking diff against the last measurement time while still using the BackgroundScheduler.

**Comment by kngoyal** [comment]
Closing for now by merging the fix [here](https://github.com/mlco2/code-carbon/commit/3ed70d941295a6bd60cf5afe510bbe1bc9b4629a)
