### ISSUE TITLE
Fail gracefully

### ISSUE THREAD

**Issue by kngoyal** [mlco2/code-carbon#32]
Failure in Code Carbon should not fail the actual user code base.

**Comment by adijo** [comment]
Can be fixed by wrapping the `start()` and `stop()` methods in a `try/catch`, logging, and ignoring the message. Something like so:

```python
@contextmanager
def suppress(*exceptions):
    try:
        yield
    except exceptions:
        logger.error(exceptions)
        pass

@suppress(Exception)
def start()
      # code
```

I'll take a look at this

**Comment by kngoyal** [comment]
Thanks @adijo , assigned it to you.

**Comment by adijo** [comment]
Done in https://github.com/mlco2/code-carbon/pull/36
